pulsar: 

  url: pulsar+ssl://<astra streaming url>:6651

  token: <astra stream token> 

  topic: persistent://<astra streaming name>/default/inventory



---
db: 

  id: <transactional db id>

  region: us-east1

  keyspace: <transactional db - keyspace>

  token:  <transactional db - token>





---
db2: 

  id: <analytical db id>

  region: us-east1

  keyspace: <analytical db - keyspace>

  token: <analytical db - token>
